### ISSUE TITLE
TypeError: 'BertTokenizerFast' object is not callable

### ISSUE THREAD

**Issue by williamhoole** [Rishabbh-Sahu/intent_and_slot_classification#2]
Hi, 
i get the following error when running flask_api.py: TypeError: 'BertTokenizerFast' object is not callable.
I'm not sure if this has to do with the version of transformers i am using. 
What version did you use for this project ?

**Comment by Rishabbh-Sahu** [comment]
Hello, Thanks for noticing this. 
I'm not very sure but it looks like I used `v4.5.1` version. There have been a lot of updates to this library lately, You can please check with this version, hope this will help.

**Comment by williamhoole** [comment]
Hi, sorry for the late reply. This helped me solve the problem.
